services:
  postgres:
    image: postgres:16
    container_name: retailflow_postgres
    environment:
      POSTGRES_USER: retailflow
      POSTGRES_PASSWORD: retailflow
      POSTGRES_DB: retailflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - retailflow_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: retailflow_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@retailflow.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - retailflow_network

  fastapi:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: retailflow_fastapi
    environment:
      DATABASE_URL: postgresql+psycopg2://retailflow:retailflow@postgres:5432/retailflow_db
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - retailflow_network

  streamlit:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    container_name: retailflow_streamlit
    environment:
      API_URL: http://fastapi:8000
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - retailflow_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  retailflow_network:
    driver: bridge
