from pathlib import Path

import pandas as pd
import streamlit as st

from components import (
    load_css,
    section_title,
    info_card,
    proof_card,
    block_badges,
    technical_evidence,
    academic_mapping,
    tool_links,
    footer_note,
)


st.set_page_config(
    page_title="RetailFlow CI/CD and Operations",
    page_icon="⚙️",
    layout="wide",
)

load_css()


def candidate_roots():
    roots = [Path.cwd()]
    try:
        roots.append(Path(__file__).resolve().parents[2])
    except Exception:
        pass
    return roots


def find_repo_file(relative_path: str):
    for root in candidate_roots():
        path = root / relative_path
        if path.exists():
            return path
    return None


def file_status(relative_path: str):
    path = find_repo_file(relative_path)
    return "available" if path else "not available in runtime"


st.title("⚙️ CI/CD and Operations")
block_badges(["Bloc 2", "Bloc 4"])

st.markdown(
    """
    Cette page regroupe les preuves d'industrialisation : pipeline CI/CD,
    validation de repository, build Docker, rapports sécurité, configuration,
    opérations PostgreSQL et documentation d'exploitation.
    """
)

section_title("CI/CD overview")

ci_jobs = [
    {
        "Job": "Python tests and syntax checks",
        "Role": "Compile Python code and run automated tests",
        "Evidence": "pytest, compileall, JUnit report",
    },
    {
        "Job": "Repository quality checks",
        "Role": "Validate JSON files and Bash scripts",
        "Evidence": "JSON parser, bash -n",
    },
    {
        "Job": "Docker Compose validation",
        "Role": "Validate Docker Compose configuration",
        "Evidence": "docker compose config --quiet",
    },
    {
        "Job": "Docker image build validation",
        "Role": "Build key application images",
        "Evidence": "FastAPI, Streamlit, event consumer Dockerfiles",
    },
    {
        "Job": "Security Checks and Audit Reports",
        "Role": "Generate security reports",
        "Evidence": "pip-audit, Bandit, security-reports artifact",
    },
]

st.dataframe(pd.DataFrame(ci_jobs), use_container_width=True, hide_index=True)

c1, c2, c3, c4 = st.columns(4)

with c1:
    st.metric("CI workflow", file_status(".github/workflows/ci.yml"))

with c2:
    st.metric("CI/CD docs", file_status("docs/CI_CD.md"))

with c3:
    st.metric("Infra docs", file_status("docs/INFRA_OPERATIONS.md"))

with c4:
    st.metric("Env example", file_status(".env.example"))

section_title("Operations readiness")

operations = [
    {
        "Area": "Environment configuration",
        "Evidence": ".env.example documents local runtime variables",
        "Tool": "VSCode / Docker Compose",
    },
    {
        "Area": "Healthchecks",
        "Evidence": "Core services expose Docker healthchecks or runtime health endpoints",
        "Tool": "Docker Compose",
    },
    {
        "Area": "Database backup",
        "Evidence": "scripts/postgres_backup.sh",
        "Tool": "WSL / PostgreSQL",
    },
    {
        "Area": "Database restore",
        "Evidence": "scripts/postgres_restore.sh",
        "Tool": "WSL / PostgreSQL",
    },
    {
        "Area": "Readonly access",
        "Evidence": "retailflow_readonly role",
        "Tool": "PostgreSQL / pgAdmin",
    },
    {
        "Area": "Monitoring",
        "Evidence": "Prometheus rules and Grafana dashboards",
        "Tool": "Prometheus / Grafana",
    },
    {
        "Area": "Security reports",
        "Evidence": "pip-audit and Bandit reports generated by CI",
        "Tool": "GitHub Actions",
    },
]

st.dataframe(pd.DataFrame(operations), use_container_width=True, hide_index=True)

section_title("Security reports")

s1, s2, s3 = st.columns(3)

with s1:
    proof_card(
        "pip-audit",
        "Audite les dépendances Python et génère un rapport artefacts.",
    )

with s2:
    proof_card(
        "Bandit",
        "Analyse du code Python afin de détecter les patterns sensibles ou à risque du point de vue sécurité.",
    )

with s3:
    proof_card(
        "Continuous security checks",
        "La CI exécute des contrôles de sécurité automatisés afin de détecter les vulnérabilités Python et les patterns de code à risque.",
    )

section_title("Operational documentation")

docs = [
    {
        "Document": "CI_CD.md",
        "Path": "docs/CI_CD.md",
        "Status": file_status("docs/CI_CD.md"),
    },
    {
        "Document": "INFRA_OPERATIONS.md",
        "Path": "docs/INFRA_OPERATIONS.md",
        "Status": file_status("docs/INFRA_OPERATIONS.md"),
    },
    {
        "Document": "MONITORING.md",
        "Path": "docs/MONITORING.md",
        "Status": file_status("docs/MONITORING.md"),
    },
    {
        "Document": "MONITORING_EVIDENCE.md",
        "Path": "docs/MONITORING_EVIDENCE.md",
        "Status": file_status("docs/MONITORING_EVIDENCE.md"),
    },
]

st.dataframe(pd.DataFrame(docs), use_container_width=True, hide_index=True)

section_title("Tools")

tool_links(
    [
        {"label": "GitHub Actions", "url": "https://github.com/HugoB-AS/retailflow-platform/actions"},
        {"label": "FastAPI Docs", "url": "http://127.0.0.1:8000/docs"},
        {"label": "Airflow", "url": "http://127.0.0.1:8080"},
        {"label": "Grafana", "url": "http://127.0.0.1:3000"},
        {"label": "Prometheus", "url": "http://127.0.0.1:9090"},
    ]
)

section_title("What this page demonstrates")

d1, d2, d3 = st.columns(3)

with d1:
    info_card(
        "CI/CD",
        "Code quality, tests, Docker validation and security reports are automated in GitHub Actions.",
    )

with d2:
    info_card(
        "Operations",
        "Backup, restore, configuration and access-control practices are documented and versioned.",
    )

with d3:
    info_card(
        "Industrialization",
        "RetailFlow is structured as a maintainable platform rather than a one-off notebook demo.",
    )

academic_mapping(
    [
        {
            "Bloc": "Bloc 2",
            "Section": "Operations readiness",
            "Preuve": "Configuration, backup/restore, healthchecks, readonly access and documentation.",
        },
        {
            "Bloc": "Bloc 4",
            "Section": "CI/CD overview",
            "Preuve": "Automated testing, Docker build validation and security reporting.",
        },
        {
            "Bloc": "Bloc 4",
            "Section": "Security reports",
            "Preuve": "pip-audit and Bandit reports generated as GitHub Actions artifacts.",
        },
    ]
)

technical_evidence(
    {
        "CI/CD files": [
            "`.github/workflows/ci.yml`",
            "`docs/CI_CD.md`",
        ],
        "Operations files": [
            "`.env.example`",
            "`scripts/postgres_backup.sh`",
            "`scripts/postgres_restore.sh`",
            "`docs/INFRA_OPERATIONS.md`",
        ],
        "Monitoring files": [
            "`monitoring/prometheus/prometheus.yml`",
            "`monitoring/prometheus/rules/retailflow_alerts.yml`",
            "`monitoring/grafana/dashboards/`",
        ],
        "Where to check": [
            "`GitHub > retailflow-platform > Actions`",
            "`VSCode > .github/workflows/ci.yml`",
            "`VSCode > docs/`",
            "`Docker Compose > services health`",
        ],
    }
)

footer_note()
